### ISSUE TITLE
[BUG] `file.append` `makedirs` doesn't work.

### ISSUE THREAD

**Issue by johnmckenna-snd** [gogrlx/grlx#112]
**Please describe the issue.**
If try to make a file and it's directories it doesn't wok.

```yaml
# doesn't work where prom-config doesn't exist
# returns error: ERROR        json: cannot unmarshal object into Go struct field StepCompletion.Error of type error        listener.go:74
steps:
  create-boilerplate-file:
    file.append:
      - name: /home/sensor/prom-config/prometheus.yml
      - makedirs: true
      - text: "boilerplate"

# this works if it only has to create the file
steps:
  create-boilerplate-file:
    file.append:
      - name: /home/sensor/prometheus.yml
      - makedirs: true
      - text: "boilerplate"
```

**Does this bug exist on the tip of master?**
[x] Yes
[ ] No

Please note that bugfixes will only be ported to previous major versions at the request of a Sponsor, and only when applicable and possible.
It is recommended all grlx users run the lastest stable release to take advantage of the newest features and bug fixes.

**Configuration**

Please upload the configuration files used if applicable.
